"""GSim -- Generic Simulator: a UI and HTTP API over the `core` framework."""

#: Single source of truth for the version, used by the API's OpenAPI document
#: (`api/app.py`), the .exe's file-version resource and the MSI's
#: ProductVersion (both generated by `scripts/build_installer.ps1`).
#:
#: MSI upgrade rules only compare the first three fields, so keep this a plain
#: `major.minor.patch` -- a fourth field or a suffix like "1.2.0-rc1" would make
#: two different builds look identical to the installer and the upgrade would
#: be skipped.
__version__ = "0.1.0"
